use crate::core::{BatchId, CostEstimate, Task, TaskId, WorkerTier};
use chrono::{DateTime, Local};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::path::Path;

/// A batch of tasks that can be executed in parallel
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskBatch {
    pub id: BatchId,
    pub tasks: Vec<Task>,
    pub tier: WorkerTier,
    pub dependencies: Vec<BatchId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BatchStatus>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BatchStatus {
    Pending,
    InProgress,
    Completed,
    Failed,
    Skipped,
}

/// Complete execution plan generated by orchestrator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub id: String,
    pub created_at: DateTime<Local>,
    pub task_description: String,
    pub analysis: String,
    pub batches: Vec<TaskBatch>,
    pub total_cost_estimate: CostEstimate,
    pub status: PlanStatus,
    #[serde(default)]
    pub validation_attempts: usize,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum PlanStatus {
    Draft,
    ValidationFailed,
    Approved,
    InProgress,
    Completed,
    Failed,
    Cancelled,
}

/// Validation error types
#[derive(Debug, thiserror::Error)]
pub enum ValidationError {
    #[error("Tasks in batch {batch_id} both modify file: {file:?}")]
    FileOverlap {
        batch_id: BatchId,
        file: std::path::PathBuf,
    },

    #[error("Batch {batch_id} depends on non-existent batch {dependency_id}")]
    MissingDependency {
        batch_id: BatchId,
        dependency_id: BatchId,
    },

    #[error("Circular dependency detected involving batch {batch_id}")]
    CircularDependency { batch_id: BatchId },
}

impl ExecutionPlan {
    /// Create a new execution plan
    pub fn new(task_description: String) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            created_at: Local::now(),
            task_description,
            analysis: String::new(),
            batches: Vec::new(),
            total_cost_estimate: CostEstimate::default(),
            status: PlanStatus::Draft,
            validation_attempts: 0,
        }
    }

    /// Validate: no two tasks in a batch touch the same file
    pub fn validate(&self) -> Result<(), ValidationError> {
        for batch in &self.batches {
            let mut files: HashSet<&Path> = HashSet::new();
            for task in &batch.tasks {
                for output in &task.expected_outputs {
                    if !files.insert(output.as_path()) {
                        return Err(ValidationError::FileOverlap {
                            batch_id: batch.id,
                            file: output.clone(),
                        });
                    }
                }
            }
        }

        // Validate dependencies exist and no circular deps
        self.validate_dependencies()?;

        Ok(())
    }

    /// Validate that all dependencies exist and there are no cycles
    fn validate_dependencies(&self) -> Result<(), ValidationError> {
        let batch_ids: HashSet<BatchId> = self.batches.iter().map(|b| b.id).collect();

        // Check all dependencies exist
        for batch in &self.batches {
            for dep_id in &batch.dependencies {
                if !batch_ids.contains(dep_id) {
                    return Err(ValidationError::MissingDependency {
                        batch_id: batch.id,
                        dependency_id: *dep_id,
                    });
                }
            }
        }

        // Check for circular dependencies using Kahn's algorithm
        if let Err(cycle_batch) = self.topological_sort() {
            return Err(ValidationError::CircularDependency {
                batch_id: cycle_batch,
            });
        }

        Ok(())
    }

    /// Sort batches in topological order (dependencies first)
    ///
    /// Uses Kahn's algorithm. Returns Err(batch_id) if a cycle is detected.
    pub fn topological_sort(&self) -> Result<Vec<&TaskBatch>, BatchId> {
        let mut in_degree: HashMap<BatchId, usize> = HashMap::new();
        let mut graph: HashMap<BatchId, Vec<BatchId>> = HashMap::new();

        // Initialize in-degrees
        for batch in &self.batches {
            in_degree.entry(batch.id).or_insert(0);
            for dep in &batch.dependencies {
                *in_degree.entry(batch.id).or_insert(0) += 1;
                graph.entry(*dep).or_default().push(batch.id);
            }
        }

        // Find all nodes with in-degree 0
        let mut queue: Vec<BatchId> = in_degree
            .iter()
            .filter(|(_, deg)| **deg == 0)
            .map(|(&id, _)| id)
            .collect();

        let mut sorted = Vec::new();

        while let Some(batch_id) = queue.pop() {
            // Find the batch
            if let Some(batch) = self.batches.iter().find(|b| b.id == batch_id) {
                sorted.push(batch);
            }

            // Reduce in-degree of neighbors
            if let Some(neighbors) = graph.get(&batch_id) {
                for &neighbor in neighbors {
                    if let Some(deg) = in_degree.get_mut(&neighbor) {
                        *deg -= 1;
                        if *deg == 0 {
                            queue.push(neighbor);
                        }
                    }
                }
            }
        }

        // Check if all batches were sorted (no cycle)
        if sorted.len() != self.batches.len() {
            // Find a batch that's part of a cycle
            let sorted_ids: HashSet<BatchId> = sorted.iter().map(|b| b.id).collect();
            let cycle_batch = self
                .batches
                .iter()
                .find(|b| !sorted_ids.contains(&b.id))
                .map(|b| b.id)
                .unwrap_or(0);
            return Err(cycle_batch);
        }

        Ok(sorted)
    }

    /// Get batch IDs in topological order (dependencies first)
    ///
    /// Returns Err(batch_id) if a cycle is detected.
    pub fn topological_sort_ids(&self) -> Result<Vec<BatchId>, BatchId> {
        let sorted = self.topological_sort()?;
        Ok(sorted.into_iter().map(|b| b.id).collect())
    }

    /// Save plan to markdown file
    pub fn save_to_markdown(&self, path: &Path) -> anyhow::Result<()> {
        let mut markdown = format!(
            "# Orchestrator Plan\n\n\
             **Generated:** {}  \n\
             **Session:** {}  \n\
             **Status:** {:?}\n\n\
             ## Task\n{}\n\n\
             ## Analysis\n{}\n\n\
             ## Cost Estimate\n\
             - **Total:** ${:.4} USD\n\
             - **Input Tokens:** {}\n\
             - **Output Tokens:** {}\n\n\
             ## Batches ({} total)\n\n",
            self.created_at.format("%Y-%m-%d %H:%M:%S"),
            self.id,
            self.status,
            self.task_description,
            self.analysis,
            self.total_cost_estimate.cost_usd,
            self.total_cost_estimate.input_tokens,
            self.total_cost_estimate.output_tokens,
            self.batches.len()
        );

        // Add batch details
        for batch in &self.batches {
            markdown.push_str(&format!("### Batch {} ({:?})\n\n", batch.id, batch.tier));
            for task in &batch.tasks {
                markdown.push_str(&format!("- **{}**: {}\n", task.id, task.description));
            }
            markdown.push('\n');
        }

        std::fs::write(path, markdown)?;
        Ok(())
    }
}
