use crate::core::{BatchId, CostEstimate, Task, TaskId, WorkerTier};
use chrono::{DateTime, Local};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::path::Path;

/// A batch of tasks that can be executed in parallel
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskBatch {
    pub id: BatchId,
    pub tasks: Vec<Task>,
    pub tier: WorkerTier,
    pub dependencies: Vec<BatchId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BatchStatus>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BatchStatus {
    Pending,
    InProgress,
    Completed,
    Failed,
    Skipped,
}

/// Complete execution plan generated by orchestrator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionPlan {
    pub id: String,
    pub created_at: DateTime<Local>,
    pub task_description: String,
    pub analysis: String,
    pub batches: Vec<TaskBatch>,
    pub total_cost_estimate: CostEstimate,
    pub status: PlanStatus,
    #[serde(default)]
    pub validation_attempts: usize,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum PlanStatus {
    Draft,
    ValidationFailed,
    Approved,
    InProgress,
    Completed,
    Failed,
    Cancelled,
}

/// Validation error types
#[derive(Debug, thiserror::Error)]
pub enum ValidationError {
    #[error("Tasks in batch {batch_id} both modify file: {file:?}")]
    FileOverlap {
        batch_id: BatchId,
        file: std::path::PathBuf,
    },

    #[error("Invalid batch dependency: batch {0} depends on non-existent batch {1}")]
    InvalidDependency(BatchId, BatchId),

    #[error("Circular dependency detected in batches")]
    CircularDependency,
}

impl ExecutionPlan {
    /// Create a new execution plan
    pub fn new(task_description: String) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            created_at: Local::now(),
            task_description,
            analysis: String::new(),
            batches: Vec::new(),
            total_cost_estimate: CostEstimate::default(),
            status: PlanStatus::Draft,
            validation_attempts: 0,
        }
    }

    /// Validate: no two tasks in a batch touch the same file
    pub fn validate(&self) -> Result<(), ValidationError> {
        for batch in &self.batches {
            let mut files: HashSet<&Path> = HashSet::new();
            for task in &batch.tasks {
                for output in &task.expected_outputs {
                    if !files.insert(output.as_path()) {
                        return Err(ValidationError::FileOverlap {
                            batch_id: batch.id,
                            file: output.clone(),
                        });
                    }
                }
            }
        }

        // TODO: Validate dependencies exist and no circular deps

        Ok(())
    }

    /// Save plan to markdown file
    pub fn save_to_markdown(&self, path: &Path) -> anyhow::Result<()> {
        let mut markdown = format!(
            "# Orchestrator Plan\n\n\
             **Generated:** {}  \n\
             **Session:** {}  \n\
             **Status:** {:?}\n\n\
             ## Task\n{}\n\n\
             ## Analysis\n{}\n\n\
             ## Cost Estimate\n\
             - **Total:** ${:.4} USD\n\
             - **Input Tokens:** {}\n\
             - **Output Tokens:** {}\n\n\
             ## Batches ({} total)\n\n",
            self.created_at.format("%Y-%m-%d %H:%M:%S"),
            self.id,
            self.status,
            self.task_description,
            self.analysis,
            self.total_cost_estimate.cost_usd,
            self.total_cost_estimate.input_tokens,
            self.total_cost_estimate.output_tokens,
            self.batches.len()
        );

        // Add batch details
        for batch in &self.batches {
            markdown.push_str(&format!("### Batch {} ({:?})\n\n", batch.id, batch.tier));
            for task in &batch.tasks {
                markdown.push_str(&format!("- **{}**: {}\n", task.id, task.description));
            }
            markdown.push('\n');
        }

        std::fs::write(path, markdown)?;
        Ok(())
    }
}
